### ISSUE TITLE
efab with unknown fluid

### ISSUE THREAD

**Issue by stclaus4** [McJty/EFab#13]
hey got this crash with a fluid not sure which it doesnt know about or whats written wrong
https://pastebin.com/sJ9iPGCL
could you see about making it give a line number when it throws this error.
im using a modified version FTB continum's config. tring to learn it and make it work for my own pack.
seems really tricky to get it how i wants to read it. if you cold add some flexablility this was that'd be much appreciated
https://pastebin.com/N5RJdvvR
^ this is what i have going on

**Comment by McJty** [comment]
I don't know what you mean by line numbers? The line numbers are in the stacktrace.

I think         "fluid": "creosote" is probably wrong. Should use the registry name: <modid>:<name>

**Comment by stclaus4** [comment]
what i mean by line numbers is what it does with wrongly typed lines regularly
"Use JsonReader.setLenient(true) to accept malformed JSON at line 23 column 5 path "

**Comment by stclaus4** [comment]
ok i switched it to : 
{
        "fluid": "immersiveengineering:fluidcreosote",
        "amount": 250
      }

still not taking

**Comment by stclaus4** [comment]
its odd because its pulled directly from the FTB file im trying to modify to learn from.

**Comment by stclaus4** [comment]
ya so i removed the entire creosote one and  it still throws that:

There was a severe problem during mod loading that has caused the game to fail
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EFab (efab)
Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:50)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:63)
	at mcjty.efab.recipes.StandardRecipes.jsonToFluidStack(StandardRecipes.java:197)
	at mcjty.efab.recipes.StandardRecipes.jsonToRecipe(StandardRecipes.java:324)
	at mcjty.efab.recipes.StandardRecipes.readRecipe(StandardRecipes.java:415)
	at mcjty.efab.recipes.StandardRecipes.readRecipesFromStream(StandardRecipes.java:410)
	at mcjty.efab.recipes.StandardRecipes.readRecipesConfig(StandardRecipes.java:181)
	at mcjty.efab.proxy.CommonProxy.postInit(CommonProxy.java:105)
	at mcjty.efab.proxy.ClientProxy.postInit(ClientProxy.java:59)
	at mcjty.efab.EFab.postInit(EFab.java:66)

**Comment by McJty** [comment]
This error can only occur with invalid/unknown fluids. So can you show me the recipe file again? (I mean the last one that is still giving errors)

**Comment by stclaus4** [comment]
https://pastebin.com/Fu6xXJHC

**Comment by McJty** [comment]
This is wrong. The modid is missing:

        "fluid": "latex",

**Comment by stclaus4** [comment]
im using industrial foregoing and the F3 H doesn't get me anything so i used "industrialforegoing:latex"
didn't work.

i figured that wasnt the problem FTB devs used that and it worked, i have no idea.
i think there  is a mod with some unregistered fluid

 There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from EFab (efab)
Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:50)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:63)
	at mcjty.efab.recipes.StandardRecipes.jsonToFluidStack(StandardRecipes.java:197)
	at mcjty.efab.recipes.StandardRecipes.jsonToRecipe(StandardRecipes.java:324)
	at mcjty.efab.recipes.StandardRecipes.readRecipe(StandardRecipes.java:415)
	at mcjty.efab.recipes.StandardRecipes.readRecipesFromStream(StandardRecipes.java:410)
	at mcjty.efab.recipes.StandardRecipes.readRecipesConfig(StandardRecipes.java:181)
	at mcjty.efab.proxy.CommonProxy.postInit(CommonProxy.java:105)
	at mcjty.efab.proxy.ClientProxy.postInit(ClientProxy.java:59)
	at mcjty.efab.EFab.postInit(EFab.java:66)

**Comment by stclaus4** [comment]
still a thing with you're updating
