### ISSUE TITLE
Can't craft Obsidian

### ISSUE THREAD

**Issue by ghost** [McJty/EFab#14]
eFab 0.0.37
Using the out-of-the-box eFab settings, I've tried rearranging, etc. Even when I can get the Start button to appear (instead of the ERROR message showing the gearbox-rf bug), I can't get the crafting process to start. It clicks and has no effect in-game. It does however fill the log with this message over and over (sorry, I don't know a way to collapse it or anything):

[17:13:02] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method mcjty/efab/blocks/rfcontrol/RfControlTE.getEnergyStored(Lnet/minecraft/util/EnumFacing;)I is abstract
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.AbstractMethodError: Method mcjty/efab/blocks/rfcontrol/RfControlTE.getEnergyStored(Lnet/minecraft/util/EnumFacing;)I is abstract
	at mcjty.efab.blocks.rfcontrol.RfControlTE.getEnergyStored(RfControlTE.java) ~[RfControlTE.class:?]
	at mcjty.efab.blocks.grid.GridTE.getErrorsForOutput(GridTE.java:1164) ~[GridTE.class:?]
	at mcjty.efab.blocks.grid.GridTE.getErrorState(GridTE.java:1123) ~[GridTE.class:?]
	at mcjty.efab.network.PacketReturnGridStatus.<init>(PacketReturnGridStatus.java:78) ~[PacketReturnGridStatus.class:?]
	at mcjty.efab.network.PacketGetGridStatus$Handler.handle(PacketGetGridStatus.java:47) ~[PacketGetGridStatus$Handler.class:?]
	at mcjty.efab.network.PacketGetGridStatus$Handler.lambda$onMessage$0(PacketGetGridStatus.java:38) ~[PacketGetGridStatus$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by McJty** [comment]
I need more info. What mod versions (EFab/McJtyLib/...)?

**Comment by ghost** [comment]
Sorry, eFab 0.0.37, McJtyLib 3.0.1, MC 1.12
Removing the RF requirement allowed the recipe to proceed. And I was having issues with getting the multiblock to connect through the RF blocks.
Also, the only RF provider I have in the pack right now is the methane generator from Hatchery (2.1.2). I've been crazy busy the last couple of days, but I'll see if I can try to reproduce in a more controlled environment (short mod list) after work.

Oh, and Forge 2707

**Comment by ghost** [comment]
Got a few minutes this morning.
MC 1.12
Forge 14.23.4.2707
eFab 0.0.37
Hatchery 2.1.2
JEI 4.10.0.199
McJtyLib 3.0.1

Go into creative.
Place down a basic eFab setup.
Try the Obsidian recipe.
The button says start, not error. It responds to a click, but does nothing.

I then added two more sets of RF cells and controllers (with a gen each since power doesn't seem to be shared across the multi-block) for a total of 3 of each. No change.

![2018-06-20_07 23 44](https://user-images.githubusercontent.com/15851438/41664893-3d520666-7496-11e8-8ab0-380ae10c171e.png)

I then installed Simple Generators 2.0.11a and replaced the methane with Nether Generators (with nether stars). No change.

Lastly, I removed Hatchery entirely. No change.
I also added in another cell/controller combo (4 of each now) with generators so each RF deice was connected to a generator running at 160 RF/t.

I hope this helps.
