### ISSUE TITLE
ConcurrentModificationException in dev env

### ISSUE THREAD

**Issue by LemmaEOF** [McJty/EFab#20]
In development environment, attempting to craft using RF results in issues spammed once per tick.

EFab 0.1.0
McJtyLib 3.0.3
Forge 14.23.4.2736

```java
[Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method mcjty/efab/blocks/rfcontrol/RfControlTE.getEnergyStored(Lnet/minecraft/util/EnumFacing;)I is abstract
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_144]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.AbstractMethodError: Method mcjty/efab/blocks/rfcontrol/RfControlTE.getEnergyStored(Lnet/minecraft/util/EnumFacing;)I is abstract
	at mcjty.efab.blocks.rfcontrol.RfControlTE.getEnergyStored(RfControlTE.java) ~[RfControlTE.class:?]
	at mcjty.efab.blocks.grid.GridTE.getErrorsForOutput(GridTE.java:1207) ~[GridTE.class:?]
	at mcjty.efab.blocks.grid.GridTE.getErrorState(GridTE.java:1166) ~[GridTE.class:?]
	at mcjty.efab.network.PacketReturnGridStatus.<init>(PacketReturnGridStatus.java:78) ~[PacketReturnGridStatus.class:?]
	at mcjty.efab.network.PacketGetGridStatus$Handler.handle(PacketGetGridStatus.java:47) ~[PacketGetGridStatus$Handler.class:?]
	at mcjty.efab.network.PacketGetGridStatus$Handler.lambda$onMessage$0(PacketGetGridStatus.java:38) ~[PacketGetGridStatus$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 5 more```

**Comment by LemmaEOF** [comment]
It's important to note, I do *not* have the RF api in my dev environment.

**Comment by McJty** [comment]
Ah on that case this is normal. In Dev environment the RF API is needed
